FiloSottile/mkcert

truststore_nss.go

This should fix FiloSottile/mkcert#12, because the `FirefoxProfile` glob also matches files like `profile.ini`.

truststore: check if profile is a directory before joining cert*.db

---

main.go

I was a little surprised to see `mkcert` use `~/Library/Application Support` instead of `$XDG_DATA_HOME` until I looked at the code and see it was intentional choice.
I personally think it would be good to follow the  XDG spec full and default to `~/.local/share` on macOS – rather than introducing custom behaviour – but it's ultimately up to you.
This PR offers a compromise, using `$XDG_DATA_HOME` if set, if you'd be okay with that. :-)
(I explicitly set XDG config vars in my shell, in order to try to get as many programs to use the same data storage structure as possible.)

Use $XDG_DATA_HOME on macOS if it is set.

---

main.go
truststore_java.go

This works for me locally on a Mac with Java 8 and 9. I'm going to test out a bit on linux and newer Java versions. 
```
$ ./bin/mkcert -install
Using the local CA at "/Users/adam/Library/Application Support/mkcert" ✨
The local CA is now installed in the system trust store! ⚡️
The local CA is now installed in the Firefox trust store (requires browser restart)! 🦊
The local CA is now installed in Java's trust store ☕️
$ keytool -list -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass changeit | grep -i mkcert
mkcert development ca 215883752978067404179277978616948247614, Jul 6, 2018, trustedCertEntry, 
```

support install into java cacerts file

---

truststore_windows.go

This is to address issue #42. This uses the win32 crypt API which is what Go uses elsewhere when interfacing with the OS cert store. Also, though there is a "certutil.exe" in Windows, it's not the NSS one and therefore while I reference the FF paths, I left `hasCertutil` as false for this OS in `cert.go`.
I took care to make the smallest, self-contained changes I could here for minimal Windows support. However as I mention in #45, this code could benefit from a lot of refactoring and "library-ification". I don't like panicking on error, returning bools, hardcoding CA org name, etc.

Add Windows Support

---

README.md

You can now install mkcert via MacPorts.  Just adding information on how to do so in the README.

Update README with info on how to install via MacPorts

---

README.md

Linuxbrew already packaged mkcert for Linux.
There's no need to build from source or periodically check here for updates.
Hence, it should be the preferred way to install mkcert.
I've re-phrased the README to reflect that.

Mentioned Linuxbrew as the preferred way to install mkcert on Linux

---

README.md

I love this tool and that it's so easy on macOS to use `brew install mkcert`.
I've created a Chocolatey package which is pending in review right now, but should be published very soon. ( https://chocolatey.org/packages/mkcert )
So on Windows someone can use `choco install mkcert` to install the current version or a specific version.
The choco package sources are at https://github.com/StefanScherer/choco-mkcert with a small CI pipeline to test the package in AppVeyor which was green for the 1.1.0 release https://ci.appveyor.com/project/StefanScherer/choco-mkcert/branch/master
If you want to have the choco package maintained in your repo, please let me know.

Add "choco install" for Windows

---

README.md
truststore_linux.go

Arch ca-certificates reference: https://www.archlinux.org/news/ca-certificates-update/
Working for me on Manjaro Linux 17.1.11.

Support installing to system trust store for Arch-based distros

---

README.md

Same as #63 but for [Scoop installer for Windows](https://github.com/lukesampson/scoop).
See https://github.com/lukesampson/scoop/wiki/Chocolatey-Comparison
I'm waiting for PR approval in the _extras bucket_ https://github.com/lukesampson/scoop-extras/pull/1153
the script is auto-updating and will be maintained externally.
Meanwhile the app manifest is publicly available on my fork and anyone can install it:
```ps
$ scoop install https://raw.githubusercontent.com/filippobuletto/scoop-extras/master/mkcert.json
```

Add scoop install for Windows

---

README.md

This has come up a few times so let's clarify in the docs.

docs: clarify mkcert doens't configure servers

---

README.md

Arch Linux does not support AUR helpers ([ref](https://wiki.archlinux.org/index.php/AUR_helpers)), so the README should reflect the recommended [install process](https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_packages).
I realize this is pedantic, but users should be guided towards the Arch way of installing AUR packages, and not to a single user's preferred method of managing AUR packages.
No code has been changed, only the `README.md` file has been altered.

README: AUR

---

truststore_java.go

If JAVA_HOME isn't set then keytoolPath has an invalid path. This means checkJava() fails and doesn't tell the problem clearly to the user.
Issue: https://github.com/FiloSottile/mkcert/issues/88

java: don't run keytool during check if we there isn't even one found

---

truststore_nss.go

Added FirefoxNightly.app for macOS, as similar to 'Firefox Developer Edition', it gets installed with a different name (as per brew https://github.com/Homebrew/homebrew-cask-versions/blob/8a61151ae75b0d87723e024256b036c511cd6096/Casks/firefox-nightly.rb#L112)

Add 'Firefox Nightly.app' for macOS.

---

cert.go
main.go

This PR allows email addresses to be passed in, along with IP addresses and domain names. Email addresses are added as SANs. The appropriate EKUs are added to the cert based on which types of SANs are present. To identify email addresses, I try parsing them with the `net/mail` package. This is probably overkill and I'm happy to switch to a regex if that's preferrable.
/fixes https://github.com/FiloSottile/mkcert/issues/143
/cc @jcjones

Allow email SANs for S/MIME certificates

---

README.md

$GOPATH/bin works in the simple cases, but will break if the user
specifies their own $GOBIN, or if their $GOPATH has multiple elements.
This form is also simpler. Even if the user doesn't specify their custom
$GOBIN, 'go env GOBIN' will return the correct default.

README: use $GOBIN instead of $GOPATH/bin

---

cert.go
main.go

Thank you for this awesome tool! :-)
I wanted to use it to create certificates for a Service Mesh, that is for using Istio with mTLS without using Citadel.
Therefore I needed to create certificates that have an extended key usage of client and server auth.
I also needed to have Spiffe URIs in the Subject Alternate Names.
Therefore I did the following changes:
1. Add a new flag `-server` which is enabled by default. If set to `false` and setting `-client=true` a client-only certificate would be generated, with `-client=true`  and `-server=true` (the default) a client and server certificate would be created.
2. Check the hostnames for being a URI with a non-empty scheme. In that case the name is accepted and added as a URI SAN.

Add support for certificates with client and server auth and URL SANs

---

truststore_java.go
truststore_nss.go

Based on @rfay's investigation and fix.
Fixes #192
Closes #193

truststore_nss: retry certtool with sudo when it fails due to permissions

---

README.md

Clarify position of advanced options argumnts (they won’t work if are placed after domain names)
Add example.

Add note about advanced options in README

---

truststore_nss.go

on my system I have only Firefox Nightly installed, so `/usr/bin/firefox` doesn't exist and so `hasNSS` was false and CA wasn't installed.
on my arch based system, the binary was at `/usr/bin/firefox-nightly`
https://aur.archlinux.org/packages/firefox-nightly/
it could also be at `/usr/bin/firefox-developer-edition`
see "package contents"
https://www.archlinux.org/packages/community/x86_64/firefox-developer-edition/

add firefox nightly and developer edition binary paths

---

README.md

This adds a missing `cd mkcert` in the instructions to build from source in the README document.

README: Add cd mkcert to build from source instructions

---

.travis.yml

There isn't a build for arm64 Linux at the moment. This PR adds support for arm64. More details: https://github.com/golang/go/wiki/GoArm

Build mkcert for arm64 Linux

---

truststore_nss.go

The latest versions of Firefox Developer Edition on macOS seem to use upper camel case naming for the app. This ensures that the CA will be added to the Firefox trust store if using recent versions of FF Dev Edition.

Support camel-case name variant of Firefox Dev Edition

---

main.go

Currently "mkcert -help" prints to stderr, which is rather annoying as:
$ mkcert -help | less
Gives us a blank page, as it pipes only stdout. To get any results in
less I need to use:
$ mkcert 2>&1 | less
$ mkcert |& less     # Non-standard bash/ zsh
Since the user explicitly asked for help with -help, it doesn't make
much sense to output it to stderr IMHO.

Make mkcert -help print to stdout instead of stderr

---

cert.go

Especially for testing I find it much more convenient to just store both
the key and certificate in a single file, which works with pretty much
all software I've used.
Currently, the -cert-file will overwrite the -key-file since it uses
ioutil.WriteFile(). This fixes it to *append* if the files are
identical.

Don't overwrite the -key-file if it's identical to -cert-file

---

README.md

Homebrew was formerly referred to as Linuxbrew when running on Linux or WSL.

Linuxbrew -> Homebrew on Linux

---

.github/workflows/release.yml

Go 1.17 [added support for Windows arm64](https://golang.org/doc/go1.17#windows). This PR adds Windows arm64 to the CI pipeline.

Add Windows arm64 build to CI pipeline
